package docker

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/chmajster/DevBox-Uniwersal/backend/internal/providers"
)

const composeDatabaseMarker = "# Generated by DevBox database binding. Contains runtime secrets; do not copy or commit.\n"

type composeDatabaseService struct {
	Image  string            `json:"image"`
	Labels map[string]string `json:"labels"`
	Ports  []struct {
		Target int `json:"target"`
	} `json:"ports"`
	Expose []any `json:"expose"`
}

func (p *CLIProvider) InspectComposeServices(ctx context.Context, directory, projectName string) ([]string, error) {
	data, err := p.originalComposeConfigJSON(ctx, directory, projectName)
	if err != nil {
		return nil, err
	}
	var config struct {
		Services map[string]composeDatabaseService `json:"services"`
	}
	if err := json.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("decode Compose services: %w", err)
	}
	names := make([]string, 0, len(config.Services))
	for name := range config.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	return names, nil
}

func (p *CLIProvider) ConfigureComposeDatabase(ctx context.Context, directory, projectName string, config providers.ComposeDatabaseConfig) (func() error, error) {
	if err := validateProjectName(projectName); err != nil {
		return nil, err
	}
	service := strings.TrimSpace(config.ApplicationService)
	if service == "" {
		var err error
		service, err = p.detectComposeApplicationService(ctx, directory, projectName)
		if err != nil {
			return nil, err
		}
	}
	if err := validateServiceName(service); err != nil {
		return nil, err
	}
	services, err := p.InspectComposeServices(ctx, directory, projectName)
	if err != nil {
		return nil, err
	}
	found := false
	for _, item := range services {
		if item == service {
			found = true
			break
		}
	}
	if !found {
		return nil, fmt.Errorf("%w: Compose application service %q does not exist", ErrInvalidInput, service)
	}
	if config.Network != "" {
		if err := p.EnsureNetwork(ctx, config.Network); err != nil {
			return nil, err
		}
	}
	data, err := renderComposeDatabaseOverride(service, config.Environment, config.Network, config.HostGateway)
	if err != nil {
		return nil, err
	}
	path, err := composeDatabaseOverridePath(directory, projectName, true)
	if err != nil {
		return nil, err
	}
	previous, err := readDatabaseOverride(path)
	if err != nil {
		return nil, err
	}
	if err := writeDatabaseOverride(path, data); err != nil {
		return nil, err
	}
	cleanup := func() error {
		current, err := readDatabaseOverride(path)
		if err != nil {
			return err
		}
		if current == nil {
			return nil
		}
		if !bytes.Equal(current, data) {
			return fmt.Errorf("Compose database override changed concurrently; refusing to remove it")
		}
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	if err := p.ComposeValidate(ctx, directory, projectName); err != nil {
		_ = cleanup()
		if previous != nil {
			_ = writeDatabaseOverride(path, previous)
		}
		return nil, fmt.Errorf("validate Compose database override: %w", err)
	}
	return cleanup, nil
}

func (p *CLIProvider) TestComposeDatabase(ctx context.Context, directory, projectName, service string, connection providers.DatabaseConnection, password []byte) error {
	if err := validateServiceName(service); err != nil || service == "" {
		return fmt.Errorf("%w: Compose database service is not selected", ErrInvalidInput)
	}
	if !safeMySQLIdentifier(connection.Database) || !safeMySQLIdentifier(connection.Username) {
		return fmt.Errorf("%w: invalid database connection identifier", ErrInvalidInput)
	}
	if connection.Port < 1 || connection.Port > 65535 {
		return fmt.Errorf("%w: database port is out of range", ErrInvalidInput)
	}
	services, err := p.InspectComposeServices(ctx, directory, projectName)
	if err != nil {
		return err
	}
	exists := false
	for _, candidate := range services {
		if candidate == service {
			exists = true
			break
		}
	}
	if !exists {
		return fmt.Errorf("%w: Compose database service %q does not exist", ErrInvalidInput, service)
	}
	args, err := composeArgs(directory, projectName)
	if err != nil {
		return err
	}
	args = append(args, "exec", "-T", "-e", "MYSQL_PWD", service,
		"mysql", "--protocol=TCP", "--host", "127.0.0.1", "--port", strconv.Itoa(connection.Port),
		"--user", connection.Username, "--database", connection.Database, "--batch", "--skip-column-names", "--execute", "SELECT 1")
	out, _, err := p.runComposeEnv(ctx, map[string]string{"MYSQL_PWD": string(password)}, args...)
	if err != nil {
		return fmt.Errorf("database connection test failed: %w", err)
	}
	if strings.TrimSpace(string(out)) != "1" {
		return fmt.Errorf("database connection test failed: unexpected SELECT 1 result")
	}
	return nil
}

func (p *CLIProvider) detectComposeApplicationService(ctx context.Context, directory, projectName string) (string, error) {
	data, err := p.originalComposeConfigJSON(ctx, directory, projectName)
	if err != nil {
		return "", err
	}
	var config struct {
		Services map[string]composeDatabaseService `json:"services"`
	}
	if err := json.Unmarshal(data, &config); err != nil {
		return "", fmt.Errorf("decode Compose services: %w", err)
	}
	labelled := make([]string, 0)
	for name, service := range config.Services {
		if strings.EqualFold(strings.TrimSpace(service.Labels["io.devbox.application"]), "true") {
			labelled = append(labelled, name)
		}
	}
	sort.Strings(labelled)
	if len(labelled) == 1 {
		return labelled[0], nil
	}
	if len(labelled) > 1 {
		return "", fmt.Errorf("Compose application service is not selected: multiple services have io.devbox.application=true")
	}
	type candidate struct {
		name  string
		score int
	}
	candidates := make([]candidate, 0, len(config.Services))
	for name, service := range config.Services {
		lowerName := strings.ToLower(name)
		lowerImage := strings.ToLower(service.Image)
		if lowerName == "db" || lowerName == "database" || lowerName == "mysql" || lowerName == "mariadb" ||
			strings.Contains(lowerImage, "mysql") || strings.Contains(lowerImage, "mariadb") || strings.Contains(lowerImage, "postgres") {
			continue
		}
		score := composePortScore(name, 0)
		for _, port := range service.Ports {
			score += composePortScore(name, port.Target)
		}
		for _, exposed := range service.Expose {
			port, _ := strconv.Atoi(strings.TrimSuffix(fmt.Sprint(exposed), "/tcp"))
			score += composePortScore(name, port)
		}
		if score > 0 || len(config.Services) == 1 {
			candidates = append(candidates, candidate{name: name, score: score})
		}
	}
	sort.Slice(candidates, func(i, j int) bool {
		if candidates[i].score == candidates[j].score {
			return candidates[i].name < candidates[j].name
		}
		return candidates[i].score > candidates[j].score
	})
	if len(candidates) == 0 || len(candidates) > 1 && candidates[0].score == candidates[1].score {
		return "", fmt.Errorf("Compose application service is not selected")
	}
	return candidates[0].name, nil
}

func (p *CLIProvider) originalComposeConfigJSON(ctx context.Context, directory, projectName string) ([]byte, error) {
	if err := validateProjectName(projectName); err != nil {
		return nil, err
	}
	base, err := findComposeFile(directory)
	if err != nil {
		return nil, err
	}
	out, _, err := p.runCompose(ctx, "compose", "-p", projectName, "-f", base, "config", "--format", "json")
	if err != nil {
		return nil, fmt.Errorf("read original Compose config: %w", err)
	}
	return out, nil
}

func renderComposeDatabaseOverride(service string, environment map[string]string, network string, hostGateway bool) ([]byte, error) {
	if err := validateServiceName(service); err != nil || service == "" {
		return nil, fmt.Errorf("%w: Compose application service is required", ErrInvalidInput)
	}
	keys := make([]string, 0, len(environment))
	for key := range environment {
		if err := validateEnvironmentName(key); err != nil {
			return nil, err
		}
		if err := validateValue(environment[key], "database environment value"); err != nil {
			return nil, err
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)
	if network != "" {
		if err := validateNetworkRef(network); err != nil {
			return nil, err
		}
	}
	var text strings.Builder
	text.WriteString(composeDatabaseMarker)
	fmt.Fprintf(&text, "services:\n  %s:\n    environment:\n", strconv.Quote(service))
	for _, key := range keys {
		fmt.Fprintf(&text, "      %s: %s\n", key, strconv.Quote(environment[key]))
	}
	if hostGateway {
		text.WriteString("    extra_hosts:\n")
		fmt.Fprintf(&text, "      - %s\n", strconv.Quote("host.docker.internal:host-gateway"))
	}
	if network != "" {
		fmt.Fprintf(&text, "    networks:\n      - %s\nnetworks:\n  %s:\n    external: true\n", strconv.Quote(network), strconv.Quote(network))
	}
	return []byte(text.String()), nil
}

func composeDatabaseOverridePath(directory, projectName string, create bool) (string, error) {
	if err := validateProjectName(projectName); err != nil {
		return "", err
	}
	source, err := filepath.Abs(directory)
	if err != nil {
		return "", err
	}
	root := strings.TrimSpace(os.Getenv("DEVBOX_COMPOSE_DATABASE_DIR"))
	if root == "" {
		config, err := os.UserConfigDir()
		if err != nil {
			return "", fmt.Errorf("resolve Compose database override storage: %w", err)
		}
		root = filepath.Join(config, "devbox", "compose-database")
	}
	if !filepath.IsAbs(root) {
		return "", fmt.Errorf("DEVBOX_COMPOSE_DATABASE_DIR must be an absolute directory")
	}
	key := sha256.Sum256([]byte(source + "\x00" + projectName))
	dir := filepath.Join(root, hex.EncodeToString(key[:]))
	if create {
		if err := os.MkdirAll(root, 0o700); err != nil {
			return "", err
		}
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return "", err
		}
	}
	return filepath.Join(dir, "database.compose.yaml"), nil
}

func readDatabaseOverride(path string) ([]byte, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0o077 != 0 || info.Size() > 128*1024 {
		return nil, fmt.Errorf("%w: invalid Compose database override", ErrInvalidInput)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if !bytes.HasPrefix(data, []byte(composeDatabaseMarker)) {
		return nil, fmt.Errorf("%w: refusing unmanaged Compose database override", ErrInvalidInput)
	}
	return data, nil
}

func writeDatabaseOverride(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".database-*")
	if err != nil {
		return err
	}
	tmp := file.Name()
	defer os.Remove(tmp)
	if err := file.Chmod(0o600); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func withDatabaseOverride(directory, projectName string, args []string) ([]string, error) {
	path, err := composeDatabaseOverridePath(directory, projectName, false)
	if err != nil {
		return nil, err
	}
	data, err := readDatabaseOverride(path)
	if err != nil {
		return nil, err
	}
	if data != nil {
		args = append(args, "-f", path)
	}
	return args, nil
}

func safeMySQLIdentifier(value string) bool {
	if value == "" || len(value) > 64 {
		return false
	}
	for _, r := range value {
		if !(r >= 'A' && r <= 'Z' || r >= 'a' && r <= 'z' || r >= '0' && r <= '9' || r == '_') {
			return false
		}
	}
	return true
}
