package docker

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/chmajster/DevBox-Uniwersal/backend/internal/providers"
)

const composePortsMarker = "# Generated by DevBox port publishing. Do not edit.\n"

var _ providers.ComposePortPublisher = (*CLIProvider)(nil)
var _ providers.ComposePortOverrideSuspender = (*CLIProvider)(nil)

type composePortService struct {
	Ports []struct {
		Target   int    `json:"target"`
		Protocol string `json:"protocol"`
	} `json:"ports"`
	Expose      []any    `json:"expose"`
	NetworkMode string   `json:"network_mode"`
	Profiles    []string `json:"profiles"`
}

func (s composePortService) targets() []int {
	seen := map[int]bool{}
	for _, port := range s.Ports {
		if port.Protocol == "" || port.Protocol == "tcp" {
			seen[port.Target] = true
		}
	}
	for _, exposed := range s.Expose {
		text := fmt.Sprint(exposed)
		if strings.HasSuffix(text, "/udp") {
			continue
		}
		value, err := strconv.Atoi(strings.TrimSuffix(text, "/tcp"))
		if err == nil && value > 0 && value <= 65535 {
			seen[value] = true
		}
	}
	ports := make([]int, 0, len(seen))
	for port := range seen {
		if port > 0 && port <= 65535 {
			ports = append(ports, port)
		}
	}
	sort.Ints(ports)
	return ports
}

func (p *CLIProvider) InspectComposePortTarget(ctx context.Context, directory, projectName, service string) (providers.ComposePortTarget, error) {
	if err := validateProjectName(projectName); err != nil {
		return providers.ComposePortTarget{}, err
	}
	if err := validateServiceName(service); err != nil {
		return providers.ComposePortTarget{}, err
	}
	base, err := findComposeFile(directory)
	if err != nil {
		return providers.ComposePortTarget{}, err
	}
	// Inspect the original topology, not the previous DevBox override. Do not
	// log or persist config output: interpolation may have resolved secrets.
	output, _, err := p.runCompose(ctx, "compose", "-p", projectName, "-f", base, "config", "--format", "json")
	if err != nil {
		return providers.ComposePortTarget{}, fmt.Errorf("inspect Compose port topology (configured publishing requires Docker Compose 2.24.4+): %w", err)
	}
	return selectComposePortTarget(output, service)
}

func selectComposePortTarget(output []byte, selected string) (providers.ComposePortTarget, error) {
	var config struct {
		Services map[string]composePortService `json:"services"`
	}
	if err := json.Unmarshal(output, &config); err != nil {
		return providers.ComposePortTarget{}, fmt.Errorf("decode Compose service topology: %w", err)
	}
	if selected == "" {
		candidates := make([]string, 0)
		for name, service := range config.Services {
			if len(config.Services) == 1 {
				candidates = append(candidates, name)
				break
			}
			for _, port := range service.targets() {
				if port == 80 || port == 8080 || port == 8000 || port == 3000 || port == 5000 {
					candidates = append(candidates, name)
					break
				}
			}
		}
		if len(candidates) != 1 {
			names := make([]string, 0, len(config.Services))
			for name := range config.Services {
				names = append(names, name)
			}
			sort.Strings(names)
			return providers.ComposePortTarget{}, fmt.Errorf("select the web service in port configuration; Compose services: %s", strings.Join(names, ", "))
		}
		selected = candidates[0]
	}
	service, found := config.Services[selected]
	if !found {
		return providers.ComposePortTarget{}, fmt.Errorf("%w: Compose service %q does not exist", ErrInvalidInput, selected)
	}
	if (service.NetworkMode != "" && service.NetworkMode != "bridge") || len(service.Profiles) > 0 {
		return providers.ComposePortTarget{}, fmt.Errorf("%w: selected web service must use normal Compose networking and must not require an inactive profile", ErrInvalidInput)
	}
	ports := service.targets()
	target := 0
	for _, preferred := range []int{80, 8080, 8000, 3000, 5000} {
		for _, port := range ports {
			if preferred == port && target == 0 {
				target = port
			}
		}
	}
	if target == 0 && len(ports) == 1 && ports[0] != 443 {
		target = ports[0]
	}
	return providers.ComposePortTarget{Service: selected, ContainerPort: target}, nil
}

func composePortOverridePath(directory, projectName string, create bool) (string, error) {
	if err := validateProjectName(projectName); err != nil {
		return "", err
	}
	source, err := filepath.Abs(directory)
	if err != nil {
		return "", err
	}
	root := strings.TrimSpace(os.Getenv("DEVBOX_COMPOSE_PORTS_DIR"))
	if root == "" {
		config, err := os.UserConfigDir()
		if err != nil {
			return "", fmt.Errorf("resolve durable Compose port storage: %w", err)
		}
		root = filepath.Join(config, "devbox", "compose-ports")
	}
	if !filepath.IsAbs(root) {
		return "", fmt.Errorf("DEVBOX_COMPOSE_PORTS_DIR must be an absolute directory")
	}
	key := sha256.Sum256([]byte(source + "\x00" + projectName))
	dir := filepath.Join(root, hex.EncodeToString(key[:]))
	if create {
		if err := os.MkdirAll(root, 0o700); err != nil {
			return "", err
		}
		if info, err := os.Lstat(root); err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("invalid Compose port storage directory")
		}
		if err := os.Mkdir(dir, 0o700); err != nil && !errors.Is(err, os.ErrExist) {
			return "", err
		}
	}
	info, err := os.Lstat(dir)
	if errors.Is(err, os.ErrNotExist) && !create {
		return filepath.Join(dir, "ports.compose.yaml"), nil
	}
	if err != nil {
		return "", err
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return "", fmt.Errorf("%w: Compose port state must be a real directory", ErrInvalidInput)
	}
	return filepath.Join(dir, "ports.compose.yaml"), nil
}

func readPortOverride(path string) ([]byte, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Size() > 64*1024 {
		return nil, fmt.Errorf("%w: invalid managed Compose port override", ErrInvalidInput)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if !bytes.HasPrefix(data, []byte(composePortsMarker)) {
		return nil, fmt.Errorf("%w: refusing to overwrite an unmanaged Compose port state file", ErrInvalidInput)
	}
	return data, nil
}

func withPortOverride(directory, projectName string, args []string) ([]string, error) {
	path, err := composePortOverridePath(directory, projectName, false)
	if err != nil {
		return nil, err
	}
	data, err := readPortOverride(path)
	if err != nil {
		return nil, err
	}
	if data != nil {
		args = append(args, "-f", path)
	}
	return args, nil
}

func writePortOverride(path string, data []byte) error {
	file, err := os.CreateTemp(filepath.Dir(path), ".ports-*")
	if err != nil {
		return err
	}
	tmp := file.Name()
	defer os.Remove(tmp)
	if _, err := file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func renderComposePorts(service string, ports []providers.PublishedPort) ([]byte, error) {
	if service == "" {
		return nil, fmt.Errorf("%w: Compose service is required", ErrInvalidInput)
	}
	if err := validateServiceName(service); err != nil {
		return nil, err
	}
	if err := validatePublishedPorts(ports); err != nil {
		return nil, err
	}
	var text strings.Builder
	text.WriteString(composePortsMarker)
	fmt.Fprintf(&text, "services:\n  %s:\n    ports: !override\n", strconv.Quote(service))
	for _, port := range ports {
		fmt.Fprintf(&text, "      - target: %d\n        published: %s\n        protocol: tcp\n", port.ContainerPort, strconv.Quote(strconv.Itoa(port.HostPort)))
	}
	return []byte(text.String()), nil
}

func (p *CLIProvider) ConfigureComposePorts(ctx context.Context, directory, projectName, service string, ports []providers.PublishedPort) (func() error, error) {
	data, err := renderComposePorts(service, ports)
	if err != nil {
		return nil, err
	}
	path, err := composePortOverridePath(directory, projectName, true)
	if err != nil {
		return nil, err
	}
	previous, err := readPortOverride(path)
	if err != nil {
		return nil, err
	}
	if err := writePortOverride(path, data); err != nil {
		return nil, err
	}
	rollback := func() error {
		current, err := readPortOverride(path)
		if err != nil {
			return err
		}
		if bytes.Equal(current, previous) {
			return nil
		}
		if !bytes.Equal(current, data) {
			return fmt.Errorf("Compose override changed concurrently; refusing to overwrite it")
		}
		if previous == nil {
			err = os.Remove(path)
			if errors.Is(err, os.ErrNotExist) {
				return nil
			}
			return err
		}
		return writePortOverride(path, previous)
	}
	if err := p.ComposeValidate(ctx, directory, projectName); err != nil {
		restoreErr := rollback()
		return nil, fmt.Errorf("validate Compose port override (requires Docker Compose 2.24.4+): %w; restore: %v", err, restoreErr)
	}
	return rollback, nil
}

func (p *CLIProvider) SuspendComposePorts(directory, projectName string) (func() error, bool, error) {
	path, err := composePortOverridePath(directory, projectName, false)
	if err != nil {
		return nil, false, err
	}
	previous, err := readPortOverride(path)
	if err != nil {
		return nil, false, err
	}
	if previous == nil {
		return nil, false, nil
	}
	if err := os.Remove(path); err != nil {
		return nil, false, err
	}
	restore := func() error {
		current, err := readPortOverride(path)
		if err != nil {
			return err
		}
		if current != nil {
			return fmt.Errorf("Compose override changed concurrently; refusing to restore suspended state")
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			return err
		}
		return writePortOverride(path, previous)
	}
	return restore, true, nil
}

// An unconfigured project must not inherit a stale override left by a deleted
// project that happened to use the same slug and source directory.
func (p *CLIProvider) ClearComposePorts(directory, projectName string) error {
	path, err := composePortOverridePath(directory, projectName, false)
	if err != nil {
		return err
	}
	data, err := readPortOverride(path)
	if err != nil || data == nil {
		return err
	}
	return os.Remove(path)
}
