package projects

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/chmajster/DevBox-Uniwersal/backend/internal/containerspec"
)

const (
	devBoxGeneratedMarker = "# Generated by DevBox from Runtime settings."
	generatedComposeFile  = "compose.yaml"
	generatedDockerfile   = ".devbox/Dockerfile"
)

var projectComposeFileNames = []string{"compose.yaml", "compose.yml", "docker-compose.yml", "docker-compose.yaml"}

func generateDevBoxCompose(project Project, config RuntimeContainerConfig, workDir, revision string) (GeneratedComposeResult, error) {
	runtime := containerspec.NormalizeRuntime(config.Runtime)
	if runtime == "" {
		runtime = containerspec.NormalizeRuntime(project.Runtime)
	}
	if runtime == "" {
		return GeneratedComposeResult{}, fmt.Errorf("%w: runtime must be selected or detected before generating Docker Compose", ErrInvalidInput)
	}

	modules := make([]containerspec.Module, 0, len(config.Modules))
	for _, module := range config.Modules {
		modules = append(modules, containerspec.Module{Name: module.Name, Version: module.Version})
	}

	hostPort := 8080
	if project.Port != nil && *project.Port >= 1 && *project.Port <= 65535 {
		hostPort = *project.Port
	}

	spec, err := containerspec.GenerateManaged(
		project.ID,
		workDir,
		runtime,
		strings.TrimSpace(config.RuntimeVersion),
		modules,
		revision,
		hostPort,
	)
	if err != nil {
		return GeneratedComposeResult{}, fmt.Errorf("%w: generate managed runtime: %v", ErrInvalidInput, err)
	}

	if err := ensureComposeGenerationIsSafe(workDir); err != nil {
		return GeneratedComposeResult{}, err
	}

	dockerfilePath := filepath.Join(workDir, filepath.FromSlash(generatedDockerfile))
	if err := os.MkdirAll(filepath.Dir(dockerfilePath), 0o755); err != nil {
		return GeneratedComposeResult{}, fmt.Errorf("create DevBox compose directory: %w", err)
	}
	dockerfile := devBoxGeneratedMarker + "\n# Regenerate from DevBox Runtime settings; manual edits may be overwritten.\n" + spec.Dockerfile
	if err := writeGeneratedFile(dockerfilePath, []byte(dockerfile)); err != nil {
		return GeneratedComposeResult{}, fmt.Errorf("write generated Dockerfile: %w", err)
	}

	compose := generatedComposeYAML(project, spec, hostPort)
	composePath := filepath.Join(workDir, generatedComposeFile)
	if err := writeGeneratedFile(composePath, []byte(compose)); err != nil {
		return GeneratedComposeResult{}, fmt.Errorf("write generated Compose file: %w", err)
	}

	return GeneratedComposeResult{
		ComposePath:    generatedComposeFile,
		DockerfilePath: generatedDockerfile,
		Runtime:        spec.Runtime,
		RuntimeVersion: spec.Version,
		HostPort:       hostPort,
		ContainerPort:  spec.ContainerPort,
	}, nil
}

func generatedComposeYAML(project Project, spec containerspec.DeploymentSpec, hostPort int) string {
	return devBoxGeneratedMarker + "\n" +
		"# Regenerate from DevBox Runtime settings; manual edits may be overwritten.\n" +
		"services:\n" +
		"  app:\n" +
		"    build:\n" +
		"      context: .\n" +
		"      dockerfile: " + strconv.Quote(generatedDockerfile) + "\n" +
		"    restart: unless-stopped\n" +
		"    init: true\n" +
		"    ports:\n" +
		"      - " + strconv.Quote(strconv.Itoa(hostPort)+":"+strconv.Itoa(spec.ContainerPort)) + "\n" +
		"    labels:\n" +
		"      io.devbox.generated: " + strconv.Quote("true") + "\n" +
		"      io.devbox.managed: " + strconv.Quote("true") + "\n" +
		"      io.devbox.project: " + strconv.Quote(project.ID) + "\n" +
		"      io.devbox.runtime: " + strconv.Quote(spec.Runtime) + "\n"
}

func ensureComposeGenerationIsSafe(workDir string) error {
	target := filepath.Join(workDir, generatedComposeFile)
	for _, name := range projectComposeFileNames {
		path := filepath.Join(workDir, name)
		data, err := os.ReadFile(path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return fmt.Errorf("inspect existing Compose file %s: %w", name, err)
		}
		if path == target && strings.HasPrefix(string(data), devBoxGeneratedMarker) {
			continue
		}
		return fmt.Errorf("%w: %s already exists and is not a DevBox-generated Compose file; existing project Compose files are never overwritten", ErrInvalidInput, name)
	}

	dockerfilePath := filepath.Join(workDir, filepath.FromSlash(generatedDockerfile))
	if data, err := os.ReadFile(dockerfilePath); err == nil {
		if !strings.HasPrefix(string(data), devBoxGeneratedMarker) {
			return fmt.Errorf("%w: %s already exists and is not generated by DevBox", ErrInvalidInput, generatedDockerfile)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect generated Dockerfile: %w", err)
	}
	return nil
}

func writeGeneratedFile(path string, data []byte) error {
	return os.WriteFile(path, data, 0o644)
}
