import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { request } from '../api/client'
import { DirectoryPicker } from '../components/DirectoryPicker'
import type { CentralCredential, DeploymentMode, Project, ProjectSourceType } from '../api/types'

interface FormState { name:string; description:string; source_type:ProjectSourceType; repository_url:string; branch:string; local_path:string; runtime:string; deployment_mode:DeploymentMode; working_directory:string; build_command:string; start_command:string; healthcheck:string; auto_start:boolean; credential_id:string }
const initial:FormState={name:'',description:'',source_type:'git',repository_url:'',branch:'main',local_path:'',runtime:'',deployment_mode:'native',working_directory:'',build_command:'',start_command:'',healthcheck:'',auto_start:false,credential_id:''}
export function ProjectWizardPage(){
 const navigate=useNavigate(); const [step,setStep]=useState(1); const [form,setForm]=useState<FormState>(initial); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [directoryBrowserOpen,setDirectoryBrowserOpen]=useState(false); const [credentials,setCredentials]=useState<CentralCredential[]>([]);
 const set=<K extends keyof FormState,>(key:K,value:FormState[K])=>setForm(current=>({...current,[key]:value}))
 useEffect(()=>{request<CentralCredential[]>('/credentials').then(items=>setCredentials(items??[])).catch(()=>setCredentials([]))},[])
 async function submit(event:FormEvent){event.preventDefault();if(step<3){setStep(step+1);return}setBusy(true);setError('');try{const path=form.source_type==='local'?'/projects/import':'/projects';const project=await request<Project>(path,{method:'POST',body:JSON.stringify(form)});navigate(`/apps/${project.id}`)}catch(cause){setError(cause instanceof Error?cause.message:'Failed to create application')}finally{setBusy(false)}}
 return <form className="wizard" onSubmit={submit}><div className="page-heading"><div><h1>Dodaj aplikację</h1><p className="muted">Krok {step} z 3</p></div></div>{error&&<div className="error-banner">{error}</div>}
 {step===1&&<div className="panel form-grid"><label>Nazwa<input value={form.name} onChange={e=>set('name',e.target.value)} required/></label><label>Typ źródła<select value={form.source_type} onChange={e=>{const source=e.target.value as ProjectSourceType;set('source_type',source);if(source!=='local')setDirectoryBrowserOpen(false)}}><option value="git">Git repository</option><option value="local">Local directory</option><option value="empty">Empty project</option></select></label><label className="span-2">Opis<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label>{form.source_type==='git'&&<><label className="span-2">Repository URL<input value={form.repository_url} onChange={e=>set('repository_url',e.target.value)} required/></label><label>Branch<input value={form.branch} onChange={e=>set('branch',e.target.value)}/></label><label>Poświadczenie<select value={form.credential_id} onChange={e=>set('credential_id',e.target.value)}><option value="">Brak</option>{credentials.map(item=><option key={item.id} value={item.id}>{item.name} · {item.kind==='token'?'GitHub token':'SSH key'}</option>)}</select></label>{credentials.length===0&&<div className="span-2 muted small">Brak centralnych poświadczeń. <Link to="/credentials">Dodaj poświadczenie</Link>, a potem wróć do kreatora.</div>}</>}{form.source_type==='local'&&<>
  <div className="span-2 path-picker-field">
    <label htmlFor="local-path">Pełna ścieżka katalogu</label>
    <div className="path-picker-row">
      <input id="local-path" value={form.local_path} onChange={e=>set('local_path',e.target.value)} required/>
      <button type="button" className="secondary" onClick={()=>setDirectoryBrowserOpen(open=>!open)}>{directoryBrowserOpen?'Ukryj drzewko':'Przeglądaj…'}</button>
    </div>
  </div>
  {directoryBrowserOpen&&<div className="span-2"><DirectoryPicker value={form.local_path} onSelect={path=>set('local_path',path)} onClose={()=>setDirectoryBrowserOpen(false)}/></div>}
</>}</div>}
 {step===2&&<div className="panel form-grid"><label>Runtime<input value={form.runtime} onChange={e=>set('runtime',e.target.value)} placeholder="np. go, python, php"/></label><label>Deployment mode<select value={form.deployment_mode} onChange={e=>set('deployment_mode',e.target.value as DeploymentMode)}><option value="native">native</option><option value="docker">docker</option></select></label><label className="span-2">Working directory<input value={form.working_directory} onChange={e=>set('working_directory',e.target.value)}/></label><label className="span-2">Build command<input value={form.build_command} onChange={e=>set('build_command',e.target.value)}/></label><label className="span-2">Start command<input value={form.start_command} onChange={e=>set('start_command',e.target.value)}/></label><label className="span-2">Healthcheck<input value={form.healthcheck} onChange={e=>set('healthcheck',e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={form.auto_start} onChange={e=>set('auto_start',e.target.checked)}/> Auto start</label></div>}
 {step===3&&<div className="panel summary-grid"><div><span>Nazwa</span><strong>{form.name}</strong></div><div><span>Źródło</span><strong>{form.source_type}</strong></div><div><span>Runtime</span><strong>{form.runtime||'nie ustawiono'}</strong></div><div><span>Tryb</span><strong>{form.deployment_mode}</strong></div>{form.source_type==='git'&&<div className="span-2"><span>Repo</span><strong>{form.repository_url} · {form.branch||'default'}</strong></div>}{form.source_type==='local'&&<div className="span-2"><span>Katalog</span><strong>{form.local_path}</strong></div>}</div>}
 <div className="wizard-actions">{step>1&&<button type="button" className="secondary" onClick={()=>setStep(step-1)}>Wstecz</button>}<button type="submit" disabled={busy}>{step<3?'Dalej':busy?'Zapisywanie…':'Utwórz aplikację'}</button></div></form>
}
